1. Data Loading

In [1]:
from google.colab import files
uploaded = files.upload()

Saving Brazilian Ecommerce.zip to Brazilian Ecommerce.zip

In [2]:
import zipfile

#changes name of zip file
zip_path = "Brazilian Ecommerce.zip"

#sees files inside the zip
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
  print(zip_ref.namelist())

['olist_customers_dataset.csv', 'olist_geolocation_dataset.csv', 'olist_order_items_dataset.csv', 'olist_order_payments_dataset.csv', 'olist_order_reviews_dataset.csv', 'olist_orders_dataset.csv', 'olist_products_dataset.csv', 'olist_sellers_dataset.csv', 'product_category_name_translation.csv']

In [3]:
import zipfile

with zipfile.ZipFile("Brazilian Ecommerce.zip", 'r') as zip_ref:
    zip_ref.extractall("data")

In [4]:
import os

os.listdir("data")

['olist_order_payments_dataset.csv',
 'product_category_name_translation.csv',
 'olist_customers_dataset.csv',
 'olist_order_items_dataset.csv',
 'olist_order_reviews_dataset.csv',
 'olist_orders_dataset.csv',
 'olist_sellers_dataset.csv',
 'olist_geolocation_dataset.csv',
 'olist_products_dataset.csv']

In [5]:
import pandas as pd

customers = pd.read_csv("data/olist_customers_dataset.csv")
geolocation = pd.read_csv("data/olist_geolocation_dataset.csv")
order_reviews = pd.read_csv("data/olist_order_reviews_dataset.csv")
sellers = pd.read_csv("data/olist_sellers_dataset.csv")
order_payments = pd.read_csv("data/olist_order_payments_dataset.csv")
order_items = pd.read_csv("data/olist_order_items_dataset.csv")
products = pd.read_csv("data/olist_products_dataset.csv")
product_category = pd.read_csv("data/product_category_name_translation.csv")
orders = pd.read_csv("data/olist_orders_dataset.csv")

In [6]:
print("Orders")
orders.head()
orders.info()

print("Customers")
customers.head()
customers.info()

print("Order Items")
order_items.head()
order_items.info()

Orders
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
Customers
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
Order Items
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [7]:
print("Products")
products.head()
products.info()

print("Order Payments")
order_payments.head()
order_payments.info()

print("Category Translation")
product_category.head()
product_category.info()

Products
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB
Order Payments
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
Category Translation
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [8]:
print("Reviews")
order_reviews.head()
order_reviews.info()

print("Sellers")
sellers.head()
sellers.info()

print("Geolocation")
geolocation.head()
geolocation.info()

Reviews
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB
Sellers
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB
Geolocation
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

2. Data Cleaning & Feature Engineering

In [9]:
#creating raw copies
orders_raw = orders.copy()
customers_raw = customers.copy()
order_items_raw = order_items.copy()
payments_raw = order_payments.copy()
products_raw = products.copy()

In [10]:
#remove duplicates
orders = orders.drop_duplicates()
customers = customers.drop_duplicates()
order_items = order_items.drop_duplicates()
payments = order_payments.drop_duplicates()
products = products.drop_duplicates()

In [11]:
#convert date columns to datetime
import pandas as pd

date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
]

for col in date_cols:
  if col in orders.columns:
    orders[col] = pd.to_datetime(orders[col], errors="coerce")

In [12]:
#converting the money column to numeric

money_cols_items = ["price", "freight_value"]
for col in money_cols_items:
  if col in order_items.columns:
    order_items[col] = pd.to_numeric(order_items[col], errors="coerce")


money_cols_payments = ["payment_value"]
for col in money_cols_payments:
  if col in payments.columns:
    payments[col] = pd.to_numeric(payments[col], errors="coerce")

In [13]:
#drop the missing key IDS, this is to ensure joins work

orders = orders.dropna(subset=["order_id", "customer_id", "order_purchase_timestamp"])
customers = customers.dropna(subset=["customer_id"])
order_items = order_items.dropna(subset=["order_id", "product_id", "price"])
payments = payments.dropna(subset=["order_id", "payment_value"])

In [14]:
#defining what valid orders are
#using delivery orders for delivery time, removes cancelled/unavailable orders

valid_orders = orders[orders["order_status"].isin(["delivered"])].copy()

In [15]:
#creating dervied fields, monthly bucket and delivery time

#monthly bucket
valid_orders["order_month"] = valid_orders["order_purchase_timestamp"].dt.to_period("M").dt.to_timestamp()

#delivery time in days
valid_orders["delivery_time_days"] = (
    valid_orders["order_delivered_customer_date"] - valid_orders["order_purchase_timestamp"]
).dt.days

#sanity filter
valid_orders = valid_orders[(valid_orders["delivery_time_days"].notna()) & (valid_orders["delivery_time_days"] >= 0)]

In [16]:
# Revenue per order from items
order_revenue = (
    order_items.groupby("order_id", as_index=False)
    .agg(items_revenue=("price", "sum"))
)

# Merge into valid_orders
valid_orders_clean = valid_orders.merge(order_revenue, on="order_id", how="left")

# Drop orders that somehow have no revenue after merge
valid_orders_clean = valid_orders_clean.dropna(subset=["items_revenue"])

In [17]:
#clean table outputs
orders_clean = orders.copy()
customers_clean = customers.copy()
order_items_clean = order_items.copy()
payments_clean = payments.copy()
products_clean = products.copy()

# Analysis base table
fact_orders_clean = valid_orders_clean.copy()

In [18]:
#validation checks
print("Clean fact table rows:", len(fact_orders_clean))
print("Min month:", fact_orders_clean["order_month"].min(), "Max month:", fact_orders_clean["order_month"].max())
print("Revenue nulls:", fact_orders_clean["items_revenue"].isna().sum())
print("Delivery time nulls:", fact_orders_clean["delivery_time_days"].isna().sum())

Clean fact table rows: 96470
Min month: 2016-09-01 00:00:00 Max month: 2018-08-01 00:00:00
Revenue nulls: 0
Delivery time nulls: 0

In [19]:
#validating the relationship between the two tables
fact_orders = fact_orders_clean.copy()

In [20]:
#creating dim customers table
dim_customers = customers_clean[[
    "customer_id",
    "customer_unique_id",
    "customer_city",
    "customer_state"
]].drop_duplicates()

In [21]:
#validate the relationship between the two
fact_orders["customer_id"].isin(dim_customers["customer_id"]).all()

np.True_

3. SQL & KPI Analysis

In [22]:
import sqlite3

In [23]:
#create an in memory database
conn = sqlite3.connect(":memory:")

In [24]:
#push panda tables into SQL
fact_orders.to_sql("fact_orders", conn, index=False, if_exists="replace")
dim_customers.to_sql("dim_customers", conn, index=False, if_exists="replace")

99441

In [25]:
#total revenue
query = """
SELECT
SUM(items_revenue) AS total_revenue
FROM fact_orders;
"""

result =pd.read_sql_query(query, conn)
result

   total_revenue
0   1.322025e+07

In [27]:
#monthly revenue trend
query = """
SELECT
strftime('%Y-%m', order_month) AS order_month,
ROUND(SUM(items_revenue), 2) AS monthly_revenue
FROM fact_orders
GROUP BY strftime('%Y-%m', order_month)
ORDER BY strftime('%Y-%m', order_month);

"""
result = pd.read_sql_query(query, conn)
result

   order_month  monthly_revenue
0      2016-09           134.97
1      2016-10         40325.11
2      2016-12            10.90
3      2017-01        111798.36
4      2017-02        234223.40
5      2017-03        359198.85
6      2017-04        340669.68
7      2017-05        489159.25
8      2017-06        421923.37
9      2017-07        481604.52
10     2017-08        554699.70
11     2017-09        607399.67
12     2017-10        648247.65
13     2017-11        987648.07
14     2017-12        726033.19
15     2018-01        924645.00
16     2018-02        826437.13
17     2018-03        953356.25
18     2018-04        973534.09
19     2018-05        977544.69
20     2018-06        855591.97
21     2018-07        867486.47
22     2018-08        838576.64

In [ ]:
#total orders
query = """
SELECT
COUNT(DISTINCT order_id) AS total_orders
FROM fact_orders;
"""

result = pd.read_sql_query(query, conn)
result

   total_orders
0         96470

In [ ]:
#Average Order Value
query = """
SELECT
SUM(items_revenue) / COUNT(DISTINCT order_id) AS aov
FROM fact_orders;
"""

result = pd.read_sql_query(query, conn)
result

          aov
0  137.040001

In [ ]:
#Unqiue customers
query = """
SELECT
COUNT(DISTINCT customer_unique_id) AS unique_customers
FROM  dim_customers;
"""

result = pd.read_sql_query(query, conn)
result

   unique_customers
0             96096

In [ ]:
#repeat purchase rate
query = """
WITH customer_orders AS (
    SELECT
    dc.customer_unique_id,
    COUNT(DISTINCT fo.order_id) AS order_count
    FROM fact_orders AS fo
    JOIN dim_customers AS dc ON fo.customer_id = dc.customer_id
    GROUP BY dc.customer_unique_id
)

SELECT
    COUNT(*) AS total_customers,
    SUM(CASE WHEN order_count > 1 THEN 1 ELSE 0 END) AS repeat_customers,
    ROUND(
        100.0 * SUM(CASE WHEN order_count > 1 THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS repeat_purchase_rate_percent
FROM customer_orders;
"""
pd.read_sql_query(query, conn)

   total_customers  repeat_customers  repeat_purchase_rate_percent
0            93350              2801                           3.0

In [ ]:
#average delivery time
query = """
SELECT
ROUND(AVG(delivery_time_days), 2) AS avg_delivery_time_days
FROM fact_orders
WHERE delivery_time_days IS NOT NULL AND delivery_time_days >= 0;
"""
pd.read_sql_query(query, conn)

   avg_delivery_time_days
0                   12.09

In [28]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [29]:
kpi_query = """
WITH customer_orders AS (
    SELECT
    dc.customer_unique_id,
    COUNT(DISTINCT fo.order_id) AS order_count
    FROM fact_orders AS fo
    JOIN dim_customers AS dc ON fo.customer_id = dc.customer_id
    GROUP BY dc.customer_unique_id
)
    SELECT
    ROUND(SUM(fo.items_revenue), 2) AS total_revenue,
    COUNT(DISTINCT fo.order_id) AS total_orders,
    ROUND(SUM(fo.items_revenue) * 1.0 / COUNT(DISTINCT fo.order_id), 2) AS aov,
    COUNT(DISTINCT dc.customer_unique_id) AS unique_customers,
    ROUND(AVG(fo.delivery_time_days), 2) AS avg_delivery_time,
    ROUND(
        100.0 * SUM(CASE WHEN co.order_count > 1 THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS repeat_purchase_rate
    FROM fact_orders AS fo
    JOIN dim_customers AS dc ON fo.customer_id = dc.customer_id
JOIN customer_orders AS co ON dc.customer_unique_id = co.customer_unique_id;
"""

kpis = pd.read_sql_query(kpi_query, conn)
kpis

,total_revenue,total_orders,aov,unique_customers,avg_delivery_time,repeat_purchase_rate
0,13220248.93,96470,137.04,93350,12.09,6.14

4. Visualisation & Insights

In [31]:
fig = make_subplots(
    rows=2, cols=3,
    specs=[[{"type": "indicator"}, {"type": "indicator"}, {"type": "indicator"}],
           [{"type": "indicator"}, {"type": "indicator"}, {"type": "indicator"}]]
)

fig.add_trace(go.Indicator(mode="number", value=kpis.loc[0, "total_revenue"], title={"text": "Total Revenue"}), row=1, col=1)
fig.add_trace(go.Indicator(mode="number", value=kpis.loc[0, "total_orders"], title={"text": "Total Orders"}), row=1, col=2)
fig.add_trace(go.Indicator(mode="number", value=kpis.loc[0, "aov"], title={"text": "AOV"}), row=1, col=3)
fig.add_trace(go.Indicator(mode="number", value=kpis.loc[0, "unique_customers"], title={"text": "Unique Customers"}), row=2, col=1)
fig.add_trace(go.Indicator(mode="number", value=kpis.loc[0, "avg_delivery_time"], title={"text": "Avg Delivery Time (Days)"}), row=2, col=2)
fig.add_trace(go.Indicator(mode="number", value=kpis.loc[0, "repeat_purchase_rate"], title={"text": "Repeat Purchase Rate %"}), row=2, col=3)

fig.update_layout(height=500, title_text="E-commerce KPI Overview")
fig.show()

In [42]:
#montly review
query = """
SELECT
order_month,
ROUND(SUM(items_revenue), 2) AS monthly_revenue
FROM fact_orders
GROUP BY order_month
ORDER BY order_month;
"""
monthly_revenue = pd.read_sql_query(query, conn)
monthly_revenue["order_month"] = pd.to_datetime(monthly_revenue["order_month"])

fig = px.line(
    monthly_revenue,
    x="order_month",
    y="monthly_revenue",
    title="Monthly Revenue Trend",
    markers=True
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Revenue"
)

fig.show()

In [36]:
#orders per month
query = """
SELECT
order_month,
COUNT(DISTINCT order_id) AS total_orders
FROM fact_orders
GROUP BY order_month
ORDER BY order_month;
"""

orders_monthly = pd.read_sql_query(query, conn)
orders_monthly["order_month"] = pd.to_datetime(orders_monthly["order_month"])

fig = px.bar(
    orders_monthly,
    x="order_month",
    y="total_orders",
    title="Orders per Month"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Orders"
)

fig.show()

In [37]:
#repeat vs one time customers
query = """
WITH customer_orders AS (
    SELECT
        dc.customer_unique_id,
        COUNT(DISTINCT fo.order_id) AS order_count
    FROM fact_orders fo
    JOIN dim_customers dc
        ON fo.customer_id = dc.customer_id
    GROUP BY dc.customer_unique_id
)
SELECT
    CASE
        WHEN order_count > 1 THEN 'Repeat'
        ELSE 'One-time'
    END AS customer_type,
    COUNT(*) AS customer_count
FROM customer_orders
GROUP BY customer_type;
"""

customer_mix = pd.read_sql_query(query, conn)

fig = px.pie(
    customer_mix,
    names="customer_type",
    values="customer_count",
    title="Repeat vs One-time Customers"
)

fig.show()

In [38]:
#delivery time distribution
query = """
SELECT delivery_time_days
FROM fact_orders
WHERE delivery_time_days IS NOT NULL
  AND delivery_time_days >= 0;
"""

delivery_df = pd.read_sql_query(query, conn)

fig = px.histogram(
    delivery_df,
    x="delivery_time_days",
    nbins=30,
    title="Distribution of Delivery Time"
)

fig.update_layout(
    xaxis_title="Delivery Time (Days)",
    yaxis_title="Number of Orders"
)

fig.show()